name: Send Punch Front Page

on:
  workflow_dispatch:

jobs:
  send-cover:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Send front page
        env:
          GREEN_API_ID_INSTANCE: ${{ secrets.GREEN_API_ID_INSTANCE }}
          GREEN_API_TOKEN: ${{ secrets.GREEN_API_TOKEN }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        run: python cover.py